### PR TITLE
Add Giso Directory Attribute

### PR DESCRIPTION
**Pull request by jhanm12**
Add Giso Directory Attribute

### CODE REVIEW

**Comment by shreyashah** [comment]
Refer this PR https://github.com/cafykit/cafy-pytest/pull/5/files
u need to map the new config variable to CafyLog variable

Also, create a private env with this branch and check if the new cmd line argument is being set as expected

**Comment by jhanm12** [comment]
Tested the changes by creating a private virtual environment - http://allure.cisco.com/auto/cafy-ott/Boot-Giso/cafykit/work/archive/test_giso_creation_20220609-062946_p32414/reports/index.html

**Comment by jhanm12** [comment]
Related Cafykit PR - https://wwwin-github.cisco.com/cafy/cafykit/pull/22364

**Comment by jhanm12** [comment]
The Private Virtual Environment -->

cd /auto/cafy-ott/Boot-Giso
source yourenv/bin/activate

**Review by shreyashah — APPROVED** [review]

**Pull request merged**
