### PR TITLE
reopening gta

### PR DESCRIPTION
**Pull request by pashupati123**
1. Feature description and need for this PR
Cafy Test Reporting: Granular Time Accounting report at the end of CAFY runs.
-> capture the time for set and get methods of feature class during run time of testcases
Doc: http://cafy-web-sjc1/pages/Cafykit/Develop/granular_time_reporting

2. Proposed changes
1: Added time capturing logic in meta.py with the help of existing decorator.
2: During run time/execution of testcase , when set or get level commands of features classes called - timer for capturing the time will start with the help of wrapper present in meta.py and after end of method timer will stop.
3: Time will be updated in the cafylog dic (gta_dict) , which will be updated in GTA html page through plugin code.

3. What type of testing has been done?
yes - Tested GTA using Cafyap , cafykit and cafykit infra ut using Toast API

4. Please attach a UT file

**GTA Test Log**

**Cafyap Test Log using —cafygta**

1: platform/envmon/envmon_ap.py
Cafy-run: https://cafy3.cisco.com/report/1650966/2183283
gta json data: [http://allure.cisco.com](http://allure.cisco.com/ws/pasverma-bgl/lldp_ap_20220926-092845_p23745/model_coverage.json)/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2183283/ut_folder-20240428T1109439222404956/cafy_gta.json

2:mgbl/netconf_violet/violet_netconf_ap.py
Cafy-run : https://cafy3.cisco.com/report/1652217/2184737
gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2184737/ut_folder-20240429T1521335615474701/cafy_gta.json

3: mgbl/gnmi_violet/violet_gnmi_ap.py
Cafy-run: https://cafy3.cisco.com/report/1652231/2184755
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2184755/ut_folder-20240429T1521335772684380/cafy_gta.json

4: l2/connectivity/span/span_local_ap.py
Cafy-run :https://cafy3.cisco.com/report/1655851/2188948
GTA json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2188948/ut_folder-20240501T2103175522136326/cafy_gta.json

**Cafykit Test Log using —cafygta**

1: test/feature_lib/lldp
1.1 test/feature_lib/lldp/lldp_ydk_test.py
Cafy-run: https://cafy3.cisco.com/report/1652175/2184677
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2184677/ut_folder-20240429T1546501127551642/cafy_gta.json
1.2 test/feature_lib/lldp/lldp_oc_test.py
Cafy-run: https://cafy3.cisco.com/report/1652175/2184677
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2184677/ut_folder-20240429T1530313123131752/cafy_gta.json
1.3: test/feature_lib/lldp/test_lldp.py
Cafy-run: https://cafy3.cisco.com/report/1652175/2184677
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2184677/ut_folder-20240429T1452301466387171/cafy_gta.json

2: test/hw/fpd/test_fpd.py
Cafy-run: https://cafy3.cisco.com/report/1653169/2185804
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185804/ut_folder-20240429T2207436189421839/cafy_gta.json

3: test/hw/obfl/obfl_test.py
Cafy-run: https://cafy3.cisco.com/report/1653185/2185821
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185821/ut_folder-20240429T2220014307949268/cafy_gta.json

4: test/feature_lib/ntp/
4.1 test/feature_lib/ntp/test_ntp.py
Cay-run:https://cafy3.cisco.com/report/1653301/2185950
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185950/ut_folder-20240430T0004568364463594/cafy_gta.json

4.2: test/feature_lib/ntp/test_ntp_oc.py
Cafy-run:https://cafy3.cisco.com/report/1653301/2185950
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185950/ut_folder-20240430T0043099564467355/cafy_gta.json

4.3: test/feature_lib/ntp/test_ntp_ydk.py
Cafy-run: https://cafy3.cisco.com/report/1653301/2185950
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185950/ut_folder-20240430T0101122694611932/cafy_gta.json

5: test/feature_lib/cdp
5.1 test/feature_lib/cdp/cdp_test.py
Cafy-run: https://cafy3.cisco.com/report/1653314/2185974
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185974/ut_folder-20240430T0008391615582703/cafy_gta.json

5.2: test/feature_lib/cdp/cdp_test_ydk.py
Cafy run: https://cafy3.cisco.com/report/1653314/2185974
Gta json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185974/ut_folder-20240430T0038223537829214/cafy_gta.json

6: test/hw/inventory/inventory_test.py
Cafy run:https://cafy3.cisco.com/report/1653327/2185988
GTA ison data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-4/cafy3-run-2185988/ut_folder-20240430T0013595486108437/cafy_gta.json

**Cafykit - infra test using —cafygta**

1: cydiff
All.log: http://allure.cisco.com/auto/cafy-ott/pasverma_gta/cafykit/work/archive/_20240502-005359_p2953546/all.log
Gta json data: http://allure.cisco.com/auto/cafy-ott/pasverma_gta/cafykit/work/archive/_20240502-005359_p2953546/cafy_gta.json
2: Parsers
All.log: http://allure.cisco.com/auto/cafy-ott/pasverma_gta/cafykit/work/archive/_20240502-005822_p2955173/all.log
GTA json data: http://allure.cisco.com/auto/cafy-ott/pasverma_gta/cafykit/work/archive/_20240502-005822_p2955173/cafy_gta.json

**VXR SIM Launch using --cafygta**

PP VXR sim launch using —cafygta
Cafygta json data: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/PP/cafy_gta.json
all.log: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/PP/all.log

F3 VXR sim launch using —cafygta
Cafygta json data: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/F3/cafy_gta.json
all.log: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/F3/all.log

**GTA UT - Non Cafykit UT Test** 
Log:
Screenshot 2024-05-03 at 7 31 25 PM

**GTA UT - Cafykit UT Test Log**
Log:
Screenshot 2024-05-03 at 7 35 55 PM

   GTA Json data: http://allure.cisco.com//ws/pasverma-bgl/test_gta_20240503-100955_p3564621/cafy_gta.json

**Test Log for Micro sec:**
1: cafyap//mgbl/gnmi_violet/violet_gnmi_ap.py
    gta_json data: http://allure.cisco.com//auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218852/ut_folder-20240521T2222335895898969/cafy_gta.json
    Toast run: https://cafy3.cisco.com/report/1680636/2218852

2: cafyap//platform/envmon/envmon_ap.py 
   gta_json_data: http://allure.cisco.com//auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218851/ut_folder-20240521T2222335089117287/cafy_gta.json
   Toast run: https://cafy3.cisco.com/report/1680635/2218851

3: test/feature_lib/cdp/cdp_test.py
gta_json_data: http://allure.cisco.com//auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218830/ut_folder-20240521T2201041921069853/cafy_gta.json
Toast run: https://cafy3.cisco.com/report/1680616/2218830

4: test/feature_lib/cdp/cdp_test_ydk.py
 gta_json_data: http://allure.cisco.com//auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218830/ut_folder-20240521T2228219983857772/cafy_gta.json
  Toast run:  https://cafy3.cisco.com/report/1680616/2218830

5: test/feature_lib/lldp/test_lldp.py
  gta_json_data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218833/ut_folder-20240521T2205015593654283/cafy_gta.json
  Toast run: https://cafy3.cisco.com/report/1680618/2218833

6: test/feature_lib/lldp/lldp_oc_test.py
  gta_json_data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218833/ut_folder-20240521T2243412763685116/cafy_gta.json
Toast Run: https://cafy3.cisco.com/report/1680618/2218833

7: test/feature_lib/lldp/lldp_ydk_test.py
gta_json data: http://allure.cisco.com/auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218833/ut_folder-20240521T2301444331371558/cafy_gta.json
Toast run: https://cafy3.cisco.com/report/1680618/2218833

8: test/hw/fpd/test_fpd.py
gta_json_data: http://allure.cisco.com//auto/cafy-sjc/cafy_log/cafy3/24-5/cafy3-run-2218834/ut_folder-20240521T2213441137896471/cafy_gta.json
Toast run: https://cafy3.cisco.com/report/1680619/2218834

**GTA TIME:**
**result when using —cafygta:**
real	0m40.083s
user	0m11.360s
sys	0m1.176s
**result when not using —cafygta**
real	0m38.076s
user	0m10.885s
sys	0m1.201s

### CODE REVIEW

**Comment by nishantupadhyay123** [comment]
add GTA and non-GTA for vxr runs.

**Comment by nishantupadhyay123** [comment]
sanity run also needs to be done.

**Comment by pashupati123** [comment]
> sanity run also needs to be done.

**Comment by pashupati123** [comment]
> add GTA and non-GTA for vxr runs.

PP VXR sim launch using —cafygta
Cafygta json data: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/PP/cafy_gta.json
all.log: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/PP/all.log

F3 VXR sim launch using —cafygta
Cafygta json data: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/F3/cafy_gta.json
all.log: http://allure.cisco.com//auto/cafy-ott/pasverma_gta/F3/all.log

**Review by nishantupadhyay123 — APPROVED** [review]

**Pull request merged**
